ALTER TABLE CONTACTTYPE OWNER TO test;
ALTER TABLE CONTACTNATREL OWNER TO test;
ALTER TABLE CONTACTCTYPEREL OWNER TO test;
ALTER TABLE NATIONALITY OWNER TO test;
ALTER TABLE CONTACT OWNER TO test;
ALTER TABLE CONTACTADDRESDETAIL OWNER TO test;
ALTER TABLE SEQUENCE OWNER TO test;
