<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.inepex</groupId>
  <version>1.2.0</version>
  <artifactId>ineall</artifactId>
  <packaging>pom</packaging>

  <scm>
    <connection>scm:git:git@github.com:inepex/ineform.git</connection>
  </scm>

  <modules>
    <module>../inei18n</module>
    <module>../ineom</module>
    <module>../ineframe</module>
    <module>../ineform</module>
  </modules>

	<properties>
		<gwtVersion>2.12.1</gwtVersion>
		<gwtGroupId>org.gwtproject</gwtGroupId>
		<jUnitVersion>4.13.2</jUnitVersion>
		<jUnitJupiterVersion>5.11.4</jUnitJupiterVersion>
		<mockitoVersion>5.23.0</mockitoVersion>
		<simpleCaptchaVersion>1.1.1</simpleCaptchaVersion>
		<daggerVersion>2.57</daggerVersion>
		<guiceVersion>7.0.0</guiceVersion>
		<gwtDndVersion>3.3.0</gwtDndVersion>
		<commonsFileUpload2Version>2.0.0-M5</commonsFileUpload2Version>
		<commonsCollectionsVersion>3.2.2</commonsCollectionsVersion>
		<commonsIoVersion>2.18.0</commonsIoVersion>
		<jakartaServletVersion>6.0.0</jakartaServletVersion>
		<jakartaPersistenceVersion>3.2.0</jakartaPersistenceVersion>
		<mavenCompilerVersion>3.13.0</mavenCompilerVersion>
		<mavenCompilerSourceVersion>17</mavenCompilerSourceVersion>
		<mavenCompilerTargetVersion>17</mavenCompilerTargetVersion>
		<mavenJarVersion>3.4.2</mavenJarVersion>
		<mavenSureFireVersion>3.5.2</mavenSureFireVersion>
		<hibernateVersion>7.0.0.Final</hibernateVersion>
		<slf4jVersion>2.0.17</slf4jVersion>
		<velocityVersion>2.4.1</velocityVersion>
		<gwtDispatchVersion>1.1.0</gwtDispatchVersion>
		<jukitoVersion>1.5</jukitoVersion>
		<googleGuavaVersion>33.4.0-jre</googleGuavaVersion>
		<buildHelperVersion>3.6.0</buildHelperVersion>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<buildNumberVersion>3.2.1</buildNumberVersion>
		<jacksonVersion>2.18.3</jacksonVersion>
		<mongoJavaDriverVersion>5.6.4</mongoJavaDriverVersion>
		<bouncyCastelVersion>1.83</bouncyCastelVersion>
		<bouncyCastelProvVersion>1.83</bouncyCastelProvVersion>
	</properties>

  <profiles>
    <profile>
      <id>buildnum</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>buildnumber-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <repositories>
    <repository>
      <id>mavencentral</id>
      <url>https://repo.maven.apache.org/maven2/</url>
      <name>Maven central</name>
    </repository>
<!--    <repository>-->
<!--      <id>maven.springframework.org.external</id>-->
<!--      <url>https://maven.springframework.org/external</url>-->
<!--      <name>SpringSource Maven Repository - External Releases</name>-->
<!--    </repository>-->
    <repository>
      <id>inepex</id>
      <url>https://maven.inepex.com/repository/public</url>
      <name>inepex</name>
    </repository>
    <repository>
      <id>sonatype-nexus-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/comgooglegwtinject-268/</url>
      <name>Sonatype Nexus Snapshots</name>
    </repository>
  </repositories>

  <distributionManagement>
    <repository>
      <id>inepex-internal</id>
      <name>Inepex Repository</name>
      <url>https://maven.inepex.com/repository/external</url>
    </repository>
  </distributionManagement>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>buildnumber-maven-plugin</artifactId>
          <version>${buildNumberVersion}</version>
          <executions>
            <execution>
              <phase>validate</phase>
              <goals>
                <goal>create</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <doCheck>true</doCheck>
            <doUpdate>false</doUpdate>
            <shortRevisionLength>9</shortRevisionLength>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
